# Generated by Django 2.2.6 on 2020-02-20 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusBlock',
            fields=[
                ('ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullDate', models.DateField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('dayOfWeek', models.IntegerField()),
                ('dayOfYear', models.IntegerField()),
                ('quarter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=150)),
                ('row', models.IntegerField()),
                ('fileName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MoonCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moonPhase', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('weatherCode', models.IntegerField(primary_key=True, serialize=False)),
                ('weatherType', models.CharField(max_length=50)),
                ('dayIcon', models.CharField(max_length=50)),
                ('nightIcon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherDegrees', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('precipitation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cloudCover', models.IntegerField()),
                ('dark', models.BooleanField()),
                ('moonPhase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.MoonCycle')),
                ('weatherType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.WeatherType')),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimeDescription', models.CharField(default='Undefined', max_length=150)),
                ('arrest', models.BooleanField()),
                ('longitude', models.DecimalField(decimal_places=9, default=0, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=9, default=0, max_digits=15)),
                ('censusBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.CensusBlock')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.City')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.CrimeType')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.Date')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.Time')),
                ('weatherDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.Weather')),
            ],
        ),
        migrations.CreateModel(
            name='CensusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deprevationIndex', models.IntegerField()),
                ('population', models.IntegerField()),
                ('censusBlockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.CensusBlock')),
            ],
        ),
    ]
