# Generated by Django 2.2.6 on 2020-01-23 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=150)),
                ('row', models.IntegerField()),
                ('fileName', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.AddField(
            model_name='crime',
            name='uniqueID',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
