# Generated by Django 2.2.6 on 2020-02-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusdata',
            name='population',
        ),
    ]
