# Generated by Django 2.2.6 on 2020-03-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0003_auto_20200305_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_visualization.City'),
        ),
    ]
