# Generated by Django 2.2.6 on 2019-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=15)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
