# Generated by Django 2.2.6 on 2019-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('block', models.CharField(max_length=100)),
                ('locationDescription', models.CharField(default='Unknown', max_length=50)),
                ('arrest', models.BooleanField()),
                ('domestic', models.BooleanField()),
                ('beat', models.CharField(default='Unknown', max_length=50)),
                ('descOne', models.CharField(default='Unknown', max_length=100)),
                ('descTwo', models.CharField(default='Unknown', max_length=100)),
                ('communityArea', models.IntegerField(default=0)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=15)),
            ],
        ),
    ]
