# Generated by Django 2.2.6 on 2019-10-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='crimes',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
    ]
